### ISSUE TITLE
Tracking User Action For Post Models for notification  

### ISSUE THREAD

**Issue by Abhishek-Gawade-programmer** [Abhishek-Gawade-programmer/socialfly-instagram-clone#15]
### Tracking User Action For Post Models
***
when user 
- [x]  create the post
- [x]   delete the post
- [x]   like some post
- [x]  tag other user
- [x] report the post
- [x] comment on post
-#14
